[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
type = "web"
envVars = []

[[services.ports]]
port = 7860
type = "HTTP"
